# -*- coding: utf-8 -*-
from __future__ import annotations

# Compatibility facade: keep the historical import path while the implementation
# is split by responsibility.
from mcdr2restic.config.config_loader import (
    get_command_root,
    load_config,
    load_config_mapping,
    replace_or_append_enabled_line,
    save_enabled_unlocked,
    strip_comment_keys,
)
from mcdr2restic.config.config_migration import (
    apply_config_file_migrations,
    ensure_config_version_tail,
    ensure_discord_block,
    ensure_force_schedule_block,
    ensure_restic_migration_lines,
    ensure_restic_timeout_value,
    ensure_restore_block,
    ensure_schedule_migration_lines,
    ensure_snapshot_cache_block,
    ensure_update_check_block,
    find_top_level_block,
    has_nested_key,
    has_top_level_key,
    insert_before_config_version_or_end,
    insert_before_top_level_key,
    insert_into_top_level_block,
    migrate_config_file,
    migrate_legacy_config,
    remove_deprecated_schedule_lines,
)
from mcdr2restic.config.config_paths import ensure_config_file_exists, get_data_file_path
from mcdr2restic.config.config_template import (
    get_discord_block_lines,
    get_force_schedule_lines,
    get_restore_block_lines,
    get_snapshot_cache_block_lines,
    get_update_check_lines,
    yaml_scalar,
)
from mcdr2restic.config.state_store import (
    ensure_runtime,
    get_config_snapshot,
    load_state_file,
    load_yaml_mapping,
    merge_defaults,
    save_config_unlocked,
    save_yaml_file,
)


__all__ = [
    'apply_config_file_migrations',
    'ensure_config_file_exists',
    'ensure_config_version_tail',
    'ensure_discord_block',
    'ensure_force_schedule_block',
    'ensure_restic_migration_lines',
    'ensure_restic_timeout_value',
    'ensure_restore_block',
    'ensure_runtime',
    'ensure_schedule_migration_lines',
    'ensure_snapshot_cache_block',
    'ensure_update_check_block',
    'find_top_level_block',
    'get_command_root',
    'get_config_snapshot',
    'get_data_file_path',
    'get_discord_block_lines',
    'get_force_schedule_lines',
    'get_restore_block_lines',
    'get_snapshot_cache_block_lines',
    'get_update_check_lines',
    'has_nested_key',
    'has_top_level_key',
    'insert_before_config_version_or_end',
    'insert_before_top_level_key',
    'insert_into_top_level_block',
    'load_config',
    'load_config_mapping',
    'load_state_file',
    'load_yaml_mapping',
    'merge_defaults',
    'migrate_config_file',
    'migrate_legacy_config',
    'remove_deprecated_schedule_lines',
    'replace_or_append_enabled_line',
    'save_config_unlocked',
    'save_enabled_unlocked',
    'save_yaml_file',
    'strip_comment_keys',
    'yaml_scalar',
]
